/* Código de la interfaz de administrador, tarea planilla. Se carga desde el panel integrado según el rol. */
(function(){
  "use strict";
  /** Busca el primer elemento del documento que coincide con el selector. */
  const $=selector=>document.querySelector(selector);
  /** Convierte caracteres especiales antes de insertar texto en HTML. */
  const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  /** Calcula el IR anual por tramos de ingreso. */
  function annualIR(income){if(income<=100000)return 0;if(income<=200000)return(income-100000)*.15;if(income<=350000)return 15000+(income-200000)*.20;if(income<=500000)return 45000+(income-350000)*.25;return 82500+(income-500000)*.30}
  /** Calcula INSS, IR, deducciones y salario neto. */
  function calculate(salary){const inss=salary*.07;const ir=annualIR((salary-inss)*12)/12;const deductions=inss+ir;return{inss,ir,deductions,net:salary-deductions}}
  /** Actualiza o sincroniza el estado de la interfaz de administrador, tarea planilla. */
  function refreshEmployees(){const rows=GIMMED.getData().staff;$("#employees").innerHTML=rows.map(row=>`<option value="${esc(row.name)}">${esc(row.role||"Sin cargo")}</option>`).join("")}
  /** Actualiza la vista previa de deducciones sin guardar la planilla. */
  function preview(){const salary=Math.max(Number($("#payroll-form").elements.salary.value)||0,0),result=calculate(salary);$("#preview-salary").textContent=GIMMED.money(salary);$("#preview-inss").textContent=`-${GIMMED.money(result.inss)}`;$("#preview-ir").textContent=`-${GIMMED.money(result.ir)}`;$("#preview-deductions").textContent=`-${GIMMED.money(result.deductions)}`;$("#preview-net").textContent=GIMMED.money(result.net)}
  /** Dibuja las tablas de planilla y el historial con sus totales. */
  function render(){const rows=GIMMED.getData().payroll;const totals=rows.reduce((sum,row)=>{["salary","inss","ir","net"].forEach(key=>sum[key]+=Number(row[key]||0));return sum},{salary:0,inss:0,ir:0,net:0});
    $("#payroll-stats").innerHTML=[["Registros",rows.length],["Salarios brutos",GIMMED.money(totals.salary)],["Deducciones",GIMMED.money(totals.inss+totals.ir)],["Subtotal neto",GIMMED.money(totals.net)]].map(([label,value])=>`<article class="stat-card"><small>${label}</small><strong>${value}</strong></article>`).join("");
    $("#payroll-body").innerHTML=rows.length?rows.map(row=>`<tr><td>${esc(row.date||"Histórico")}</td><td>${esc(row.period||"Sin período")}</td><td>${esc(row.employee)}</td><td>${GIMMED.money(row.salary)}</td><td class="amount-negative">${GIMMED.money(row.inss)}</td><td class="amount-negative">${GIMMED.money(row.ir)}</td><td class="amount-negative">${GIMMED.money(Number(row.inss)+Number(row.ir))}</td><td class="amount-net">${GIMMED.money(row.net)}</td><td class="no-print"><button class="danger-button remove-payroll" data-id="${row.id}">Eliminar</button></td></tr>`).join(""):'<tr><td colspan="9" class="empty">No hay cálculos guardados.</td></tr>';
    document.querySelectorAll(".remove-payroll").forEach(button=>button.addEventListener("click",()=>{if(!confirm("¿Eliminar este cálculo?"))return;GIMMED.update(data=>data.payroll=data.payroll.filter(row=>row.id!==Number(button.dataset.id)),"Cálculo de planilla eliminado","Planilla");render()}));
    const history=GIMMED.getData().payrollHistory||[];$("#history-body").innerHTML=history.length?history.map(item=>`<tr><td>${GIMMED.formatDate(item.date)}</td><td>${esc(item.period)}</td><td>${item.rows.length}</td><td>${GIMMED.money(item.salary)}</td><td>${GIMMED.money(item.inss)}</td><td>${GIMMED.money(item.ir)}</td><td>${GIMMED.money(item.deductions)}</td><td class="amount-net">${GIMMED.money(item.net)}</td><td><button class="secondary-button load-history" data-id="${item.id}">Cargar</button> <button class="danger-button delete-history" data-id="${item.id}">Eliminar</button></td></tr>`).join(""):'<tr><td colspan="9" class="empty">Todavía no hay planillas guardadas en el historial.</td></tr>';document.querySelectorAll(".load-history").forEach(button=>button.addEventListener("click",()=>{const snapshot=history.find(item=>item.id===Number(button.dataset.id));GIMMED.update(data=>data.payroll=snapshot.rows.map(row=>({...row})),"Planilla histórica cargada","Planilla");render();GIMMED.toast("Planilla histórica cargada.")}));document.querySelectorAll(".delete-history").forEach(button=>button.addEventListener("click",()=>{if(!confirm("¿Eliminar esta planilla del historial?"))return;GIMMED.update(data=>data.payrollHistory=data.payrollHistory.filter(item=>item.id!==Number(button.dataset.id)),"Historial de planilla eliminado","Planilla");render()}));
  }
  document.addEventListener("DOMContentLoaded",()=>{GIMMED.requireAuth();GIMMED.shell("planilla");GIMMED.trackActivity();refreshEmployees();window.addEventListener("gimmed:employees-synced",refreshEmployees);void GIMMED.syncEmployees();const form=$("#payroll-form");const now=new Date();form.elements.date.value=now.toISOString().slice(0,10);form.elements.period.value=now.toISOString().slice(0,7);
    form.elements.salary.addEventListener("input",preview);form.addEventListener("submit",event=>{event.preventDefault();if(!form.reportValidity())return;const values=GIMMED.formObject(form);const salary=Number(values.salary);if(!Number.isFinite(salary)||salary<=0){$("#payroll-error").textContent="El salario debe ser mayor que cero.";return}const result=calculate(salary);GIMMED.update(current=>current.payroll.unshift({id:Date.now(),employee:values.employee,date:values.date,period:values.period,salary,...result}),`Planilla calculada: ${values.employee}`,"Planilla");form.reset();form.elements.date.value=now.toISOString().slice(0,10);form.elements.period.value=now.toISOString().slice(0,7);$("#payroll-error").textContent="";preview();render()});
    $("#save-history").addEventListener("click",()=>{const data=GIMMED.getData();if(!data.payroll.length)return GIMMED.toast("Agregue empleados antes de guardar el historial.","error");const totals=data.payroll.reduce((sum,row)=>{sum.salary+=Number(row.salary);sum.inss+=Number(row.inss);sum.ir+=Number(row.ir);sum.deductions+=Number(row.deductions||Number(row.inss)+Number(row.ir));sum.net+=Number(row.net);return sum},{salary:0,inss:0,ir:0,deductions:0,net:0}),first=data.payroll[0];GIMMED.update(current=>current.payrollHistory.unshift({id:Date.now(),date:first.date||GIMMED.today(),period:first.period||GIMMED.today().slice(0,7),rows:data.payroll.map(row=>({...row})),...totals}),"Planilla guardada en historial","Planilla");render();GIMMED.toast("Planilla guardada en el historial.")});
    $("#print-payroll").addEventListener("click",()=>GIMMED.printPDF("Planilla IR e INSS - GIM-MED"));preview();render();});
})();
