/* Código de la interfaz de administrador, tarea control acceso. Se carga desde el panel integrado según el rol. */
(function(){
  "use strict";
  /** Busca el primer elemento del documento que coincide con el selector. */
  const $=selector=>document.querySelector(selector);
  /** Coordina la operación duration de la interfaz de administrador, tarea control acceso. */
  function duration(seconds){const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return`${hours} h ${String(minutes).padStart(2,"0")} min`}
  /** Convierte una fecha al formato mostrado en la interfaz. */
  function date(value){return value?new Date(value).toLocaleString("es-NI"):"En uso"}
  /** Coordina la operación scheduledSeconds de la interfaz de administrador, tarea control acceso. */
  function scheduledSeconds(staff){if(!staff?.startTime||!staff?.endTime)return 0;const[startHour,startMinute]=staff.startTime.split(":").map(Number),[endHour,endMinute]=staff.endTime.split(":").map(Number);let minutes=endHour*60+endMinute-(startHour*60+startMinute);if(minutes<0)minutes+=1440;return Math.max(minutes,0)*60}
  /** Actualiza la pantalla de la interfaz de administrador, tarea control acceso con los datos disponibles. */
  function render(){const data=GIMMED.getData(),rows=data.access.map(session=>{const employee=data.staff.find(item=>item.email?.toLowerCase()===(session.email||"").toLowerCase()),scheduled=scheduledSeconds(employee);return{...session,employee,scheduled,overtime:Math.max(0,Number(session.seconds||0)-scheduled)}}),active=rows.filter(x=>x.status==="Activa").length,total=rows.reduce((s,x)=>s+Number(x.seconds||0),0),overtime=rows.reduce((s,x)=>s+x.overtime,0);$("#access-stats").innerHTML=[["Sesiones registradas",rows.length],["Usuarios en el sistema",active],["Tiempo activo acumulado",duration(total)],["Horas extra estimadas",duration(overtime)]].map(([a,b],index)=>`<article class="stat-card ${index===0?"featured":""}"><small>${a}</small><strong>${b}</strong></article>`).join("");$("#access-body").innerHTML=rows.length?rows.map(row=>`<tr><td><strong>${GIMMED.escapeHTML(row.user)}</strong><small>${GIMMED.escapeHTML(row.username||"")} · ${GIMMED.escapeHTML(row.role)}</small></td><td>${date(row.login)}</td><td>${date(row.lastActivity)}</td><td>${date(row.logout)}</td><td><strong>${duration(row.seconds||0)}</strong></td><td>${row.employee?`${GIMMED.escapeHTML(row.employee.startTime)}-${GIMMED.escapeHTML(row.employee.endTime)}`:"Sin vínculo"}</td><td class="overtime">${duration(row.overtime)}</td><td><span class="status-badge">${GIMMED.escapeHTML(row.status)}</span></td></tr>`).join(""):'<tr><td colspan="8" class="empty">El historial comenzará con el próximo inicio de sesión.</td></tr>'}
  document.addEventListener("DOMContentLoaded",()=>{GIMMED.requireAuth();GIMMED.shell("control-acceso");GIMMED.trackActivity();render();window.addEventListener("gimmed:employees-synced",render);void GIMMED.syncEmployees();setInterval(render,30000);$("#access-pdf").addEventListener("click",()=>GIMMED.printPDF("Control de acceso y tiempo activo GIM-MED"));});
})();
