-- Cada proyecto usa su propia copia de esta base de datos SQLite.
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS accounts (
 id INTEGER PRIMARY KEY, username TEXT NOT NULL UNIQUE COLLATE NOCASE,
 display_name TEXT NOT NULL, role TEXT NOT NULL,
 password_salt TEXT NOT NULL, password_hash TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS patients (
 id INTEGER PRIMARY KEY, file_number TEXT NOT NULL UNIQUE,
 full_name TEXT NOT NULL, identification TEXT DEFAULT '',
 payload TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS resources (
 id INTEGER PRIMARY KEY, kind TEXT NOT NULL, payload TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS resources_kind ON resources(kind);
CREATE TABLE IF NOT EXISTS clinical_records (
 id INTEGER PRIMARY KEY, patient_id INTEGER NOT NULL REFERENCES patients(id),
 kind TEXT NOT NULL, title TEXT NOT NULL, payload TEXT NOT NULL,
 author TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS records_patient ON clinical_records(patient_id,created_at);
CREATE TABLE IF NOT EXISTS notifications (
 id INTEGER PRIMARY KEY, title TEXT NOT NULL, message TEXT NOT NULL,
 category TEXT NOT NULL DEFAULT 'Sistema', is_read INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS beds (
 code TEXT PRIMARY KEY, label TEXT NOT NULL, area TEXT NOT NULL,
 patient_id INTEGER REFERENCES patients(id)
);
CREATE TABLE IF NOT EXISTS app_state (id INTEGER PRIMARY KEY CHECK(id=1), payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS backups (id INTEGER PRIMARY KEY, payload TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
